name: webhook
on:
   release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run Cmd
      id: runCmd
      uses: actions/checkout@v2
    - run: |
          git fetch --unshallow --tags
          branch=$(git branch -a --contains tags/25.3)
          VAR=`echo $branch | awk '{print $NF}' | awk -F "[/]" '{print $NF}'`
          echo $VAR
          echo ${GITHUB_REF##*/}
