name: webhook
on:
  repository_dispatch:
    types: do-something
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: github pull
        uses: actions/checkout@v2
      - run: |
          git pull
      - name: Create Report
        run: |
          echo "${{ github.event.client_payload.text }}" > ./PR-Report.html
          echo "File Created"
#       - name: Commit files
#         run: |
#           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git config --local user.name "github-actions[bot]"
#           git add ./report2.html
#           git commit -m "[Github-Bot] Added PR-Report"
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.event.client_payload.branch }}
